### ISSUE TITLE
stupid installation question.

### ISSUE THREAD

**Issue by larsoss** [rage2dev/YiOutdoor#1]
sorry for the stupid question, but could you make a slightly clearer install? because I can't figure it out.

**Comment by rage2dev** [comment]
There are no stupid questions ;) 

Updated repo with config.sh and "install"-chapter in the readme.

**Comment by larsoss** [comment]
Sorry. Read so many information last months. 
Dont know where to begin anymore. 
Can you give me a step by step please?

**Comment by rage2dev** [comment]
- Create a fat32 formated SD-Card
- Create folder wifi
- Copy config.sh to "wifi/"
- Insert SD-Card, reboot Cam
- telnet yourcamip -p 9999
- username: "root"
- password: EMPTY

**Comment by larsoss** [comment]
II'm sorry, I did as described, sd card formatted to fat32. After that I
created a folder WiFi and placed the file config.sh in the folder. SD card
in the camera, and turned on. After that the far too loud start-up sound
starts. I am trying telnet through the CMD prompt, this is not working. I
also get an error via Putty.
Network error: Cannot assign requested address.

**Comment by rage2dev** [comment]
"wifi" in lowercase ?

**Comment by larsoss** [comment]
yes ;-)

**Comment by rage2dev** [comment]
Looks like a network-config-problem oder putty-config-problem and has nothing to do with the cam. 

Try in the cmd :
"telnet yourcamip 9999"

**Comment by larsoss** [comment]
Ok that works..  i see now:
/home/app #

Thats it. And what is the next step?

**Comment by rage2dev** [comment]
Well, nothing or everything :) This scripts just allows telnet access. We will need the sdk from Realtek at the next step.

**Comment by larsoss** [comment]
/home/app # udhcpc -i wlan0 -b -s /backup/script/default.script &
/home/app # sleep 10
udhcpc (v1.20.2) started

Setting IP address 0.0.0.0 on wlan0
Sending discover...
Sending select for 192.168.1.200...
Lease of 192.168.1.200 obtained, lease time 43200
Setting IP address 192.168.1.200 on wlan0
 need update route and dns with wlan0
Deleting routers
Adding router 192.168.1.1
Recreating /var/nm/resolv.conf
 Adding DNS server 192.168.1.1
Set DNS config
[1]+  Done                       udhcpc -i wlan0 -b -s /backup/script/default.script
/home/app # /bin/busybox telnetd -l/bin/ash -p9999 &
/home/app #


Ok, so this is good?

**Comment by rage2dev** [comment]
Yep, thats telnet access.
